(function(g){var window=this;'use strict';var v7a=function(a,b){a.Pa("onAutonavCoundownStarted",b)},k6=function(a,b,c){g.po(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Cf(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.lH&&(b.lengthText?(e=b.lengthText||null,f=b.ut||null):b.lengthSeconds&&(e=g.zM(b.lengthSeconds),f=g.zM(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.jH(d).type;var l=b instanceof g.lH?b.isLivePlayback:null,m=b instanceof g.lH?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],w=[];n&&r.push(n);p&&(r.push(p),w.push(p));q&&w.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.bK("$TITLE afspelen",{TITLE:b.title}),duration:e,timestamp:f,url:b.Zm(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:w.join(" \u2022 "),autoplayAlternativeHeader:b.Op};b instanceof g.kH&&(c.playlist_length=b.playlistLength);a.update(c)},l6=function(a){var b=a.V(),c=b.B;
g.X.call(this,{F:"a",N:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.T:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{F:"div",Ga:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},W:[{F:"div",X:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],qa:"{{duration}}"},{F:"div",Ga:["ytp-autonav-live-stamp"],qa:"Live"},{F:"div",
Ga:["ytp-autonav-upcoming-stamp"],qa:"Binnenkort"},{F:"div",N:"ytp-autonav-list-overlay",W:[{F:"div",N:"ytp-autonav-mix-text",qa:"Mix"},{F:"div",N:"ytp-autonav-mix-icon"}]}]},{F:"div",Ga:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],qa:"{{title}}"},{F:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],qa:"{{author}}"},{F:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],qa:"{{views_and_publish_time}}"}]});this.G=a;this.suggestion=
null;this.j=c;this.Qa("click",this.onClick);this.Qa("keypress",this.onKeyPress)},m6=function(a,b){b=void 0===b?!1:b;
g.X.call(this,{F:"div",N:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.I=b;this.D=void 0;this.B=0;this.container=new g.X({F:"div",N:"ytp-autonav-endscreen-countdown-container"});g.N(this,this.container);this.container.Ca(this.element);b=a.V();var d=b.B;this.G=a;this.suggestion=null;this.onVideoDataChange("newdata",this.G.getVideoData());this.S(a,"videodatachange",this.onVideoDataChange);var e=["ytp-autonav-endscreen-upnext-thumbnail"];b.K("web_rounded_thumbnails")&&e.push("rounded-thumbnail");
this.j=new g.X({F:"div",N:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{F:"div",N:"ytp-autonav-endscreen-upnext-header"},{F:"div",N:"ytp-autonav-endscreen-upnext-alternative-header",qa:"{{autoplayAlternativeHeader}}"},{F:"a",N:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.T:""},W:[{F:"div",Ga:e,X:{style:"{{background}}"},W:[{F:"div",
X:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],qa:"{{duration}}"},{F:"div",Ga:["ytp-autonav-live-stamp"],qa:"Live"},{F:"div",Ga:["ytp-autonav-upcoming-stamp"],qa:"Binnenkort"}]},{F:"div",N:"ytp-autonav-endscreen-video-info",W:[{F:"div",N:"ytp-autonav-endscreen-premium-badge"},{F:"div",N:"ytp-autonav-endscreen-upnext-title",qa:"{{title}}"},{F:"div",N:"ytp-autonav-endscreen-upnext-author",qa:"{{author}}"},{F:"div",N:"ytp-autonav-view-and-date",qa:"{{views_and_publish_time}}"},{F:"div",
N:"ytp-autonav-author-and-view",qa:"{{author_and_views}}"}]}]}]});g.N(this,this.j);this.j.Ca(this.container.element);d||this.S(this.j.Da("ytp-autonav-endscreen-link-container"),"click",this.QM);this.G.yb(this.container.element,this,115127);this.G.yb(this.j.Da("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.X({F:"div",N:"ytp-autonav-overlay"});g.N(this,this.overlay);this.overlay.Ca(this.container.element);this.u=new g.X({F:"div",N:"ytp-autonav-endscreen-button-container"});
g.N(this,this.u);this.u.Ca(this.container.element);this.cancelButton=new g.X({F:"button",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Autoplay annuleren"},qa:"Annuleren"});g.N(this,this.cancelButton);this.cancelButton.Ca(this.u.element);this.cancelButton.Qa("click",this.pV,this);this.G.yb(this.cancelButton.element,this,115129);this.playButton=new g.X({F:"a",Ga:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Volgende video afspelen"},qa:"Nu spelen"});g.N(this,this.playButton);this.playButton.Ca(this.u.element);this.playButton.Qa("click",this.QM,this);this.G.yb(this.playButton.element,this,115130);this.C=new g.bo(function(){w7a(c)},500);
g.N(this,this.C);this.PM();this.S(a,"autonavvisibility",this.PM);this.G.K("web_autonav_color_transition")&&(this.S(a,"autonavchange",this.oV),this.S(a,"onAutonavCoundownStarted",this.z0))},n6=function(a){var b=a.G.wj(!0,a.G.isFullscreen());
g.po(a.container.element,"ytp-autonav-endscreen-small-mode",a.pg(b));g.po(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.dF);g.po(a.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.G.kf());g.po(a.G.getRootNode(),"countdown-running",a.Aj());g.po(a.container.element,"ytp-player-content",a.G.kf());g.Cl(a.overlay.element,{width:b.width+"px"});if(!a.Aj()){a.G.kf()?x7a(a,Math.round(y7a(a)/1E3)):x7a(a);b=!!a.suggestion&&!!a.suggestion.Op;var c=a.G.kf()||!b;
g.po(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.po(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.xL(a.u,a.G.kf());g.po(a.element,"ytp-enable-w2w-color-transitions",z7a(a))}},w7a=function(a){var b=y7a(a),c=Math,d=c.min;
var e=a.B?Date.now()-a.B:0;c=d.call(c,e,b);x7a(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Aj()?a.select(!0):a.Aj()&&a.C.start()},y7a=function(a){if(a.G.isFullscreen()){var b;
a=null==(b=a.G.getVideoData())?void 0:b.mM;return-1===a||void 0===a?8E3:a}return 0<=a.G.jq()?a.G.jq():g.lF(a.G.V().experiments,"autoplay_time")||1E4},z7a=function(a){var b;
return!(null==(b=a.G.getVideoData())||!b.watchToWatchTransitionRenderer)},x7a=function(a,b){b=void 0===b?-1:b;
a=a.j.Da("ytp-autonav-endscreen-upnext-header");g.dh(a);if(0<=b){b=String(b);var c="Volgende video over $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Volgende video over $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.ch("Volgende video over $SECONDS".slice(0,d)));var e=g.bh("span");g.io(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.ih(e,b);a.appendChild(e);a.appendChild(g.ch("Volgende video over $SECONDS".slice(d+c.length)));return}}g.ih(a,"Volgende")},o6=function(a,b){g.X.call(this,
{F:"div",
Ga:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},p6=function(a){g.X.call(this,{F:"div",
Ga:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},W:[{F:"div",N:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{F:"span",N:"ytp-upnext-top",W:[{F:"span",N:"ytp-upnext-header",qa:"Hierna"},{F:"span",N:"ytp-upnext-title",qa:"{{title}}"},{F:"span",N:"ytp-upnext-author",qa:"{{author}}"}]},{F:"a",N:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Volgende video afspelen"},W:[{F:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
W:[{F:"circle",N:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{F:"circle",N:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{F:"path",N:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{F:"span",N:"ytp-upnext-bottom",W:[{F:"span",N:"ytp-upnext-cancel"},{F:"span",N:"ytp-upnext-paused",
qa:"Autoplay is onderbroken"}]}]});this.api=a;this.cancelButton=null;this.D=this.Da("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.bo(this.xC,5E3,this);this.u=0;var b=this.Da("ytp-upnext-cancel");this.cancelButton=new g.X({F:"button",Ga:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Autoplay annuleren"},qa:"Annuleren"});g.N(this,this.cancelButton);this.cancelButton.Qa("click",this.qV,this);this.cancelButton.Ca(b);this.cancelButton&&
this.api.yb(this.cancelButton.element,this,115129);g.N(this,this.C);this.api.yb(this.element,this,18788);b=this.Da("ytp-upnext-autoplay-icon");this.S(b,"click",this.rV);this.api.yb(b,this,115130);this.RM();this.S(a,"autonavvisibility",this.RM);this.S(a,"mdxnowautoplaying",this.l1);this.S(a,"mdxautoplaycanceled",this.m1);g.po(this.element,"ytp-upnext-mobile",this.api.V().isMobile)},A7a=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.mM;return-1===a||void 0===a?8E3:a}return 0<=a.api.jq()?a.api.jq():g.lF(a.api.V().experiments,"autoplay_time")||1E4},B7a=function(a,b){b=A7a(a,b);
var c=Math,d=c.min;var e=(0,g.S)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Aj()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Aj()&&a.j.start()},q6=function(a){o6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.X({F:"div",N:"ytp-suggestion-panel",W:[{F:"div",Ga:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],qa:"Meer video's"}]});this.J=new g.X({F:"div",N:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new m6(this.player);g.N(this,this.u);this.u.Ca(this.element);a.getVideoData().Re?this.j=this.u:(this.j=new p6(a),g.iO(this.player,this.j.element,4),g.N(this,this.j));this.overlay=new g.X({F:"div",
N:"ytp-autonav-overlay-cancelled-state"});g.N(this,this.overlay);this.overlay.Ca(this.element);this.C=new g.mE(this);g.N(this,this.C);g.N(this,this.table);this.table.Ca(this.element);this.table.show();g.N(this,this.J);this.J.Ca(this.table.element);this.hide()},r6=function(a){var b=a.kf();
b!==a.D&&(a.D=b,a.player.ma("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},s6=function(a,b){g.X.call(this,{F:"button",
Ga:["ytp-watch-on-youtube-button","ytp-button"],X:{title:"{{message}}"},qa:"{{content}}"});this.G=a;this.buttonType=this.buttonType=b;switch(this.buttonType){case 1:a="Opnieuw bekijken op YouTube";b=156915;break;case 2:a="Verder kijken op YouTube";b=156942;break;default:a="Verder kijken op YouTube",b=156942}this.update({message:a,content:a});this.G.yb(this.element,this,b);this.Qa("click",this.onClick);g.xL(this,!0)},t6=function(a,b){o6.call(this,a,"embeds-lite-endscreen");
this.G=a;this.j=b;this.G.yb(this.element,this,156943);this.watchButton=new s6(a,2);g.N(this,this.watchButton);this.watchButton.Ca(this.element);this.hide()},C7a=function(a){o6.call(this,a,"subscribecard-endscreen");
this.j=new g.X({F:"div",N:"ytp-subscribe-card",W:[{F:"img",N:"ytp-author-image",X:{src:"{{profilePicture}}"}},{F:"div",N:"ytp-subscribe-card-right",W:[{F:"div",N:"ytp-author-name",qa:"{{author}}"},{F:"div",N:"html5-subscribe-button-container"}]}]});g.N(this,this.j);this.j.Ca(this.element);var b=a.getVideoData();this.subscribeButton=new g.SP("Abonneren",null,"Afmelden",null,!0,!1,b.Uk,b.subscribed,"trailer-endscreen",null,null,a);g.N(this,this.subscribeButton);this.subscribeButton.Ca(this.j.Da("html5-subscribe-button-container"));
this.S(a,"videodatachange",this.Ka);this.Ka();this.hide()},u6=function(a){var b=a.V(),c=g.pE||g.cG?{style:"will-change: opacity"}:void 0,d=b.B,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.X.call(this,{F:"a",Ga:e,X:{href:"{{url}}",target:d?b.T:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{F:"div",N:"ytp-videowall-still-image",X:{style:"{{background}}"}},{F:"span",N:"ytp-videowall-still-info",X:{"aria-hidden":"true"},W:[{F:"span",N:"ytp-videowall-still-info-bg",W:[{F:"span",N:"ytp-videowall-still-info-content",X:c,W:[{F:"span",N:"ytp-videowall-still-info-title",
qa:"{{title}}"},{F:"span",N:"ytp-videowall-still-info-author",qa:"{{author_and_views}}"},{F:"span",N:"ytp-videowall-still-info-live",qa:"Live"},{F:"span",N:"ytp-videowall-still-info-duration",qa:"{{duration}}"}]}]}]},{F:"span",Ga:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{F:"span",N:"ytp-videowall-still-listlabel-icon"},"Playlist",{F:"span",N:"ytp-videowall-still-listlabel-length",W:[" (",{F:"span",qa:"{{playlist_length}}"},")"]}]},{F:"span",
Ga:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{F:"span",N:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{F:"span",N:"ytp-videowall-still-listlabel-length",qa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.mE(this);g.N(this,this.j);this.Qa("click",this.onClick);this.Qa("keypress",this.onKeyPress);this.j.S(a,"videodatachange",this.onVideoDataChange);a.jg(this.element,this);this.onVideoDataChange()},v6=function(a){o6.call(this,
a,"videowall-endscreen");
var b=this;this.G=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.J=!1;this.T=null;this.u=new g.mE(this);g.N(this,this.u);this.Z=a.K("web_rounded_thumbnails");this.I=new g.bo(function(){g.ko(b.element,"ytp-show-tiles")},0);
g.N(this,this.I);var c=new g.X({F:"button",Ga:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Vorige"},W:[g.CL()]});g.N(this,c);c.Ca(this.element);c.Qa("click",this.vV,this);this.table=new g.uL({F:"div",N:"ytp-endscreen-content"});g.N(this,this.table);this.table.Ca(this.element);c=new g.X({F:"button",Ga:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Volgende"},W:[g.DL()]});g.N(this,c);c.Ca(this.element);c.Qa("click",this.uV,this);a.getVideoData().Re?this.j=new m6(a,!0):this.j=new p6(a);
g.N(this,this.j);g.iO(this.player,this.j.element,4);a.yb(this.element,this,158789);this.hide()},w6=function(a){return g.jO(a.player)&&a.Ly()&&!a.C},D7a=function(a){var b,c,d,e;
return(null==(b=a.videoData)?0:null==(c=b.suggestions)?0:c.length)?null==(d=a.videoData)?void 0:d.suggestions:[null==(e=a.videoData)?void 0:g.jI(e)]},x6=function(a){var b=a.kf();
b!==a.J&&(a.J=b,a.player.ma("autonavvisibility"))},y6=function(a){o6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new s6(a,1);g.N(this,this.watchButton);this.watchButton.Ca(this.element);g.k_a(a)&&(this.j=new g.K2(a,g.ZN(a)),g.N(this,this.j),this.u=new g.X({F:"div",Ga:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},W:[this.j]}),g.N(this,this.u),this.j.Ca(this.u.element),this.u.Ca(this.element));a.yb(this.element,this,156914);this.hide()},H7a=function(a){g.OO.call(this,a);
var b=this;this.endScreen=null;this.u=this.j=this.B=this.C=!1;this.listeners=new g.mE(this);g.N(this,this.listeners);var c=a.V();if(g.tv(g.yG(c))&&!g.fO(a))this.u=!0,this.endScreen=new t6(a,g.ZN(a));else{var d;(null==(d=g.ZN(a))?0:d.zj())?this.endScreen=new y6(a):E7a(a)?(this.C=!0,F7a(this),this.j?this.endScreen=new q6(a):this.endScreen=new v6(this.player)):c.Se?this.endScreen=new C7a(this.player):this.endScreen=new o6(this.player)}g.N(this,this.endScreen);g.iO(this.player,this.endScreen.element,
4);G7a(this);this.listeners.S(a,"videodatachange",this.onVideoDataChange,this);this.listeners.S(a,g.yA("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.S(a,g.zA("endscreen"),function(e){b.onCueRangeExit(e)})},F7a=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Yk&&a.B===b.Re)return!1;a.j=b.Yk;a.B=b.Re;return!0},E7a=function(a){a=a.V();
return a.Gc&&!a.Se},G7a=function(a){a.player.xf("endscreen");
var b=a.player.getVideoData();b=new g.wA(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.wA(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.me([b,c])};
g.TS.prototype.sx=g.ba(35,function(a){this.vK!==a&&(this.vK=a,this.Vj())});
g.SS.prototype.rp=g.ba(34,function(a){this.u!==a&&(this.u=a,this.Dy())});
g.TS.prototype.rp=g.ba(33,function(a){this.Xk&&this.Xk.rp(a)});
g.DP.prototype.YA=g.ba(32,function(a){this.wK!==a&&(this.wK=a,this.On())});
g.bO.prototype.jq=g.ba(6,function(){return this.app.jq()});
g.QY.prototype.jq=g.ba(5,function(){return this.getVideoData().IM});g.v(l6,g.X);l6.prototype.select=function(){(this.G.jm(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.gz||void 0)||this.G.K("web_player_endscreen_double_log_fix_killswitch"))&&this.G.wb(this.element)};
l6.prototype.onClick=function(a){g.oP(a,this.G,this.j,this.suggestion.sessionData||void 0)&&this.select()};
l6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Ax(a)||(this.select(),g.zx(a))}};g.v(m6,g.X);g.k=m6.prototype;g.k.HB=function(a){this.suggestion!==a&&(this.suggestion=a,k6(this.j,a),this.playButton.updateValue("url",this.suggestion.Zm()),n6(this))};
g.k.Aj=function(){return 0<this.B};
g.k.zx=function(){this.Aj()||(this.B=Date.now(),w7a(this),v7a(this.G,y7a(this)),g.po(this.G.getRootNode(),"countdown-running",this.Aj()))};
g.k.Kt=function(){this.xp();w7a(this);var a=this.j.Da("ytp-autonav-endscreen-upnext-header");a&&g.ih(a,"Volgende")};
g.k.xp=function(){this.Aj()&&(this.C.stop(),this.B=0)};
g.k.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.xp()};
g.k.QM=function(a){g.oP(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.wb(this.playButton.element):a.currentTarget===this.j.Da("ytp-autonav-endscreen-link-container")&&(a=this.j.Da("ytp-autonav-endscreen-link-container"),this.G.Va(a,!0),this.G.wb(a)),this.select())};
g.k.pV=function(){this.G.wb(this.cancelButton.element);g.dO(this.G,!0);this.D&&this.G.Pa("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.hX)?void 0:c.command};
g.k.z0=function(a){if(z7a(this)){var b=this.G.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.KM(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.KM(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.KM(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.KM(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.KM(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.KM(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.po(this.element,"ytp-w2w-animate",!0)}};
g.k.oV=function(a){this.G.K("web_autonav_color_transition")&&2!==a&&g.po(this.element,"ytp-w2w-animate",!1)};
g.k.PM=function(){var a=this.G.kf();this.I&&this.rb!==a&&g.xL(this,a);n6(this);this.G.Va(this.container.element,a);this.G.Va(this.cancelButton.element,a);this.G.Va(this.j.Da("ytp-autonav-endscreen-link-container"),a);this.G.Va(this.playButton.element,a)};
g.k.pg=function(a){return 400>a.width||459>a.height};g.v(o6,g.X);g.k=o6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Ly=function(){return!1};
g.k.kf=function(){return!1};
g.k.LQ=function(){return!1};g.v(p6,g.X);g.k=p6.prototype;g.k.xC=function(){this.notification&&(this.C.stop(),this.xc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.HB=function(a){this.suggestion=a;k6(this,a,"hqdefault.jpg")};
g.k.RM=function(){g.xL(this,this.api.kf());this.api.Va(this.element,this.api.kf());this.api.Va(this.Da("ytp-upnext-autoplay-icon"),this.api.kf());this.cancelButton&&this.api.Va(this.cancelButton.element,this.api.kf())};
g.k.w1=function(){window.focus();this.xC()};
g.k.zx=function(a){var b=this;this.Aj()||(g.Px("a11y-announce","Hierna "+this.suggestion.title),this.u=(0,g.S)(),this.j=new g.bo(function(){B7a(b,a)},25),B7a(this,a),v7a(this.api,A7a(this,a)));
g.no(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.X.prototype.hide.call(this)};
g.k.Aj=function(){return!!this.j};
g.k.Kt=function(){this.xp();this.u=(0,g.S)();B7a(this);g.ko(this.element,"ytp-upnext-autoplay-paused")};
g.k.xp=function(){this.Aj()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.V().K("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.xC(),this.notification=new Notification("Hierna",{body:this.suggestion.title,icon:this.suggestion.Cf()}),this.B=this.S(this.notification,"click",this.w1),this.C.start())}this.xp();this.api.nextVideo(!1,a)};
g.k.rV=function(a){!g.hh(this.cancelButton.element,g.vx(a))&&g.oP(a,this.api)&&(this.api.kf()&&this.api.wb(this.Da("ytp-upnext-autoplay-icon")),this.select())};
g.k.qV=function(){this.api.kf()&&this.cancelButton&&this.api.wb(this.cancelButton.element);g.dO(this.api,!0)};
g.k.l1=function(a){this.api.getPresentingPlayerType();this.show();this.zx(a)};
g.k.m1=function(){this.api.getPresentingPlayerType();this.xp();this.hide()};
g.k.ra=function(){this.xp();this.xC();g.X.prototype.ra.call(this)};g.v(q6,o6);g.k=q6.prototype;g.k.create=function(){o6.prototype.create.call(this);this.C.S(this.player,"appresize",this.iy);this.C.S(this.player,"onVideoAreaChange",this.iy);this.C.S(this.player,"videodatachange",this.onVideoDataChange);this.C.S(this.player,"autonavchange",this.SM);this.C.S(this.player,"autonavcancel",this.sV);this.onVideoDataChange()};
g.k.show=function(){o6.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.dO(this.player,!1);g.jO(this.player)&&this.Ly()&&!this.B?(r6(this),2===this.videoData.autonavState?this.player.V().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.zx():3===this.videoData.autonavState&&this.j.Kt()):(g.dO(this.player,!0),r6(this));this.iy()};
g.k.hide=function(){o6.prototype.hide.call(this);this.j.Kt();r6(this)};
g.k.iy=function(){var a=this.player.wj(!0,this.player.isFullscreen());r6(this);n6(this.u);g.po(this.element,"ytp-autonav-cancelled-small-mode",this.pg(a));g.po(this.element,"ytp-autonav-cancelled-tiny-mode",this.GD(a));g.po(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Cl(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.t(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.t(b.value);b=c.next().value;c=c.next().value;g.po(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){var b=g.jI(this.videoData);b&&(this.j.HB(b),this.j!==this.u&&this.u.HB(b));for(b=0;b<I7a.length;++b){var c=I7a[b];if(a&&a[c]){this.videos[b]=new l6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,k6(d,c));g.N(this,this.videos[b]);this.videos[b].Ca(this.J.element)}}}this.iy()}};
g.k.SM=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.j.xp(),this.rb&&this.iy()):(this.I=!0,this.kf()&&(2===a?this.j.zx():3===a&&this.j.Kt()))};
g.k.sV=function(a){a?this.SM(1):(this.B=null,this.I=!1)};
g.k.Ly=function(){return 1!==this.videoData.autonavState};
g.k.pg=function(a){return(910>a.width||459>a.height)&&!this.GD(a)&&!(400>=a.width||360>=a.height)};
g.k.GD=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.kf=function(){return this.rb&&g.jO(this.player)&&this.Ly()&&!this.B};
var I7a=[1,3,2,4];g.v(s6,g.X);g.k=s6.prototype;g.k.onClick=function(a){g.pP(this.getVideoUrl(),this.G,a);this.G.wb(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.G.getVideoUrl(a,!1,!1,!0);var b=this.G.V();if(g.eG(b)||g.pG(b)){var c={};b.Aa&&g.eG(b)&&g.vN(c,b.loaderUrl);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.uN(c,b);a=g.ki(a,c)}return a};
g.k.Va=function(){this.G.Va(this.element,this.rb&&this.Aa)};
g.k.show=function(){g.X.prototype.show.call(this);this.Va()};
g.k.hide=function(){g.X.prototype.hide.call(this);this.Va()};
g.k.Tb=function(a){g.X.prototype.Tb.call(this,a);this.Va()};g.v(t6,o6);t6.prototype.show=function(){3!==this.player.getPlayerState()&&(o6.prototype.show.call(this),this.j.sx(!0),this.j.rp(!0),this.G.Va(this.element,!0),this.watchButton.Tb(!0))};
t6.prototype.hide=function(){o6.prototype.hide.call(this);this.j.sx(!1);this.j.rp(!1);this.G.Va(this.element,!1);this.watchButton.Tb(!1)};g.v(C7a,o6);C7a.prototype.Ka=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Uk;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.v(u6,g.X);u6.prototype.select=function(){(this.api.jm(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.gz||void 0)||this.api.K("web_player_endscreen_double_log_fix_killswitch"))&&this.api.wb(this.element)};
u6.prototype.onClick=function(a){g.oP(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
u6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Ax(a)||(this.select(),g.zx(a))}};
u6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.D?!1:b.B};g.v(v6,o6);g.k=v6.prototype;g.k.create=function(){o6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Vn();this.u.S(this.player,"appresize",this.Vn);this.u.S(this.player,"onVideoAreaChange",this.Vn);this.u.S(this.player,"videodatachange",this.onVideoDataChange);this.u.S(this.player,"autonavchange",this.WF);this.u.S(this.player,"autonavcancel",this.tV);a=this.videoData.autonavState;a!==this.T&&this.WF(a);this.u.S(this.element,"transitionend",this.U2)};
g.k.destroy=function(){g.gz(this.u);g.We(this.stills);this.stills=[];o6.prototype.destroy.call(this);g.no(this.element,"ytp-show-tiles");this.I.stop();this.T=this.videoData.autonavState};
g.k.Ly=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.rb;o6.prototype.show.call(this);D7a(this);g.no(this.element,"ytp-show-tiles");this.player.V().isMobile?g.eo(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.dO(this.player,!1);w6(this)?(x6(this),2===this.videoData.autonavState?this.player.V().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.zx():3===this.videoData.autonavState&&this.j.Kt()):(g.dO(this.player,!0),x6(this));a!==this.rb&&
this.player.Va(this.element,!0)};
g.k.hide=function(){var a=this.rb;o6.prototype.hide.call(this);this.j.Kt();x6(this);a!==this.rb&&this.player.Va(this.element,!1)};
g.k.U2=function(a){g.vx(a)===this.element&&this.Vn()};
g.k.Vn=function(){var a=D7a(this);if(a.length){g.ko(this.element,"ytp-endscreen-paginate");var b=this.G.wj(!0,this.G.isFullscreen()),c=g.ZN(this.G);c&&(c=c.Df()?48:32,b.width-=2*c);var d=b.width/b.height,e=96/54,f=c=2,h=Math.max(b.width/96,2),l=Math.max(b.height/54,2),m=a.length,n=Math.pow(2,2);var p=m*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-n;for(p-=n;0<p&&(c<h||f<l);){var q=c/2,r=f/2,w=c<=h-2&&p>=r*n,y=f<=l-2&&p>=q*n;if((q+1)/r*e/d>d/(q/(r+1)*e)&&y)p-=q*n,f+=2;else if(w)p-=r*n,c+=2;else if(y)p-=q*
n,f+=2;else break}e=!1;p>=3*n&&6>=m*n-p&&(4<=f||4<=c)&&(e=!0);n=96*c;p=54*f;d=n/p<d?b.height/p:b.width/n;d=Math.min(d,2);n=Math.floor(Math.min(b.width,n*d));p=Math.floor(Math.min(b.height,p*d));b=this.table.element;b.ariaLive="polite";g.Ml(b,n,p);g.Cl(b,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.HB(g.jI(this.videoData));this.j instanceof m6&&n6(this.j);g.po(this.element,"ytp-endscreen-takeover",w6(this));x6(this);n+=4;p+=4;d=0;b.ariaBusy="true";for(h=0;h<c;h++)for(l=0;l<f;l++)if(q=d,w=0,e&&
h>=c-2&&l>=f-2?w=1:0===l%2&&0===h%2&&(2>l&&2>h?0===l&&0===h&&(w=2):w=2),q=g.yg(q+this.B,m),0!==w){r=this.stills[d];r||(r=new u6(this.player),this.stills[d]=r,b.appendChild(r.element));y=Math.floor(p*l/f);var z=Math.floor(n*h/c),B=Math.floor(p*(l+w)/f)-y-4,D=Math.floor(n*(h+w)/c)-z-4;g.Il(r.element,z,y);g.Ml(r.element,D,B);g.Cl(r.element,"transitionDelay",(l+h)/20+"s");g.po(r.element,"ytp-videowall-still-mini",1===w);g.po(r.element,"ytp-videowall-still-large",2<w);this.Z&&(w=Math.max(D,B),g.po(r.element,
"ytp-videowall-still-round-large",256<=w),g.po(r.element,"ytp-videowall-still-round-medium",96<w&&256>w),g.po(r.element,"ytp-videowall-still-round-small",96>=w));q=a[q];r.suggestion!==q&&(r.suggestion=q,w=r.api.V(),y=g.jo(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",k6(r,q,y),g.eG(w)&&(y=q.Zm(),z={},w.Aa&&g.vN(z,w.loaderUrl),y=g.ki(y,g.uN(z,"emb_rel_end")),r.updateValue("url",y)),(q=(q=q.sessionData)&&q.itct)&&r.api.rh(r.element,q));d++}b.ariaBusy="false";g.po(this.element,
"ytp-endscreen-paginate",d<m);for(a=this.stills.length-1;a>=d;a--)c=this.stills[a],g.fh(c.element),g.Ve(c);this.stills.length=d}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Vn())};
g.k.uV=function(){this.B+=this.stills.length;this.Vn()};
g.k.vV=function(){this.B-=this.stills.length;this.Vn()};
g.k.LQ=function(){return this.j.Aj()};
g.k.WF=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.xp(),this.rb&&this.Vn()):(this.D=!0,this.rb&&w6(this)&&(2===a?this.j.zx():3===a&&this.j.Kt()))};
g.k.tV=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.Va(this.stills[a].element,!0);this.WF(1)}else this.C=null,this.D=!1;this.Vn()};
g.k.kf=function(){return this.rb&&w6(this)};g.v(y6,o6);y6.prototype.show=function(){if(3!==this.player.getPlayerState()){o6.prototype.show.call(this);var a=this.u;if(a){var b=0<this.j.suggestionData.length;g.po(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.ZN(this.player))||c.YA(!0);this.player.Va(this.element,!0);this.watchButton.Tb(!0)}};
y6.prototype.hide=function(){o6.prototype.hide.call(this);var a;null==(a=g.ZN(this.player))||a.YA(!1);this.player.Va(this.element,!1);this.watchButton.Tb(!1)};g.v(H7a,g.OO);g.k=H7a.prototype;g.k.fu=function(){var a;if((null==(a=g.ZN(this.player))?0:a.zj())||this.u)return!0;a=this.player.getVideoData();var b;var c=!!((null==a?0:g.jI(a))||(null==a?0:null==(b=a.suggestions)?0:b.length));b=!E7a(this.player)||c;c=a.Yh||g.pG(a.u);var d=this.player.pz();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.kf=function(){return this.endScreen.kf()};
g.k.k_=function(){return this.kf()?this.endScreen.LQ():!1};
g.k.ra=function(){this.player.xf("endscreen");g.OO.prototype.ra.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.tb().xe.get("heartbeat"),d=g.jI(a);!d||b.videoId!==d.videoId||a.MQ?(this.player.jm(b.videoId,void 0,void 0,!0,!0,b),c&&c.MD("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.OO.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.OO.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.fu()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){G7a(this);this.C&&F7a(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new q6(this.player):this.endScreen=new v6(this.player),g.N(this,this.endScreen),g.iO(this.player,this.endScreen.element,4))};g.NO("endscreen",H7a);})(_yt_player);
